"""empty message

Revision ID: 2b813e313bbc
Revises: c889e960b9a8
Create Date: 2022-05-18 09:46:50.480649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b813e313bbc'
down_revision = 'c889e960b9a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('headline', sa.String(length=75), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'headline')
    # ### end Alembic commands ###
