"""empty message

Revision ID: a0f7d82cb9ae
Revises: 81aaef020a64
Create Date: 2022-05-13 09:59:15.576889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f7d82cb9ae'
down_revision = '81aaef020a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_instructions', sa.String(length=1000), nullable=False))
    op.add_column('products', sa.Column('image_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_url')
    op.drop_column('orders', 'delivery_instructions')
    # ### end Alembic commands ###
